server:
  port: 8080
  servlet:
    context-path: /springdemo


spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/mytest
        username: admin
        password: admin
    mvc:
      view:
        prefix: /WEB-INF/views/
        suffix: .jsp


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.springdemo.entity

