package com.example.entity;

import java.math.BigDecimal;
import java.util.Date;

public class eppbplan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ep_pb_plan.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ep_pb_plan.planId
     *
     * @mbggenerated
     */
    private String planid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ep_pb_plan.applyDept
     *
     * @mbggenerated
     */
    private String applydept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ep_pb_plan.groupType
     *
     * @mbggenerated
     */
    private String grouptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ep_pb_plan.visitTask
     *
     * @mbggenerated
     */
    private String visittask;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ep_pb_plan.ifInstitution
     *
     * @mbggenerated
     */
    private String ifinstitution;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ep_pb_plan.visitTime
     *
     * @mbggenerated
     */
    private Date visittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ep_pb_plan.visitDays
     *
     * @mbggenerated
     */
    private BigDecimal visitdays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ep_pb_plan.personNums
     *
     * @mbggenerated
     */
    private Short personnums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ep_pb_plan.leader
     *
     * @mbggenerated
     */
    private String leader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ep_pb_plan.leaderPosition
     *
     * @mbggenerated
     */
    private String leaderposition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ep_pb_plan.fillDept
     *
     * @mbggenerated
     */
    private String filldept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ep_pb_plan.demo
     *
     * @mbggenerated
     */
    private String demo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ep_pb_plan.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ep_pb_plan.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ep_pb_plan.createPerson
     *
     * @mbggenerated
     */
    private String createperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ep_pb_plan.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ep_pb_plan.updatePerson
     *
     * @mbggenerated
     */
    private String updateperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ep_pb_plan.exportStatus
     *
     * @mbggenerated
     */
    private String exportstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ep_pb_plan.exportLog
     *
     * @mbggenerated
     */
    private String exportlog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ep_pb_plan.exportDate
     *
     * @mbggenerated
     */
    private Date exportdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ep_pb_plan.fillPersonName
     *
     * @mbggenerated
     */
    private String fillpersonname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ep_pb_plan.fillPersonPhone
     *
     * @mbggenerated
     */
    private String fillpersonphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ep_pb_plan.expLogId
     *
     * @mbggenerated
     */
    private String explogid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ep_pb_plan.id
     *
     * @return the value of ep_pb_plan.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ep_pb_plan.id
     *
     * @param id the value for ep_pb_plan.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ep_pb_plan.planId
     *
     * @return the value of ep_pb_plan.planId
     *
     * @mbggenerated
     */
    public String getPlanid() {
        return planid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ep_pb_plan.planId
     *
     * @param planid the value for ep_pb_plan.planId
     *
     * @mbggenerated
     */
    public void setPlanid(String planid) {
        this.planid = planid == null ? null : planid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ep_pb_plan.applyDept
     *
     * @return the value of ep_pb_plan.applyDept
     *
     * @mbggenerated
     */
    public String getApplydept() {
        return applydept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ep_pb_plan.applyDept
     *
     * @param applydept the value for ep_pb_plan.applyDept
     *
     * @mbggenerated
     */
    public void setApplydept(String applydept) {
        this.applydept = applydept == null ? null : applydept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ep_pb_plan.groupType
     *
     * @return the value of ep_pb_plan.groupType
     *
     * @mbggenerated
     */
    public String getGrouptype() {
        return grouptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ep_pb_plan.groupType
     *
     * @param grouptype the value for ep_pb_plan.groupType
     *
     * @mbggenerated
     */
    public void setGrouptype(String grouptype) {
        this.grouptype = grouptype == null ? null : grouptype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ep_pb_plan.visitTask
     *
     * @return the value of ep_pb_plan.visitTask
     *
     * @mbggenerated
     */
    public String getVisittask() {
        return visittask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ep_pb_plan.visitTask
     *
     * @param visittask the value for ep_pb_plan.visitTask
     *
     * @mbggenerated
     */
    public void setVisittask(String visittask) {
        this.visittask = visittask == null ? null : visittask.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ep_pb_plan.ifInstitution
     *
     * @return the value of ep_pb_plan.ifInstitution
     *
     * @mbggenerated
     */
    public String getIfinstitution() {
        return ifinstitution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ep_pb_plan.ifInstitution
     *
     * @param ifinstitution the value for ep_pb_plan.ifInstitution
     *
     * @mbggenerated
     */
    public void setIfinstitution(String ifinstitution) {
        this.ifinstitution = ifinstitution == null ? null : ifinstitution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ep_pb_plan.visitTime
     *
     * @return the value of ep_pb_plan.visitTime
     *
     * @mbggenerated
     */
    public Date getVisittime() {
        return visittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ep_pb_plan.visitTime
     *
     * @param visittime the value for ep_pb_plan.visitTime
     *
     * @mbggenerated
     */
    public void setVisittime(Date visittime) {
        this.visittime = visittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ep_pb_plan.visitDays
     *
     * @return the value of ep_pb_plan.visitDays
     *
     * @mbggenerated
     */
    public BigDecimal getVisitdays() {
        return visitdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ep_pb_plan.visitDays
     *
     * @param visitdays the value for ep_pb_plan.visitDays
     *
     * @mbggenerated
     */
    public void setVisitdays(BigDecimal visitdays) {
        this.visitdays = visitdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ep_pb_plan.personNums
     *
     * @return the value of ep_pb_plan.personNums
     *
     * @mbggenerated
     */
    public Short getPersonnums() {
        return personnums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ep_pb_plan.personNums
     *
     * @param personnums the value for ep_pb_plan.personNums
     *
     * @mbggenerated
     */
    public void setPersonnums(Short personnums) {
        this.personnums = personnums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ep_pb_plan.leader
     *
     * @return the value of ep_pb_plan.leader
     *
     * @mbggenerated
     */
    public String getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ep_pb_plan.leader
     *
     * @param leader the value for ep_pb_plan.leader
     *
     * @mbggenerated
     */
    public void setLeader(String leader) {
        this.leader = leader == null ? null : leader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ep_pb_plan.leaderPosition
     *
     * @return the value of ep_pb_plan.leaderPosition
     *
     * @mbggenerated
     */
    public String getLeaderposition() {
        return leaderposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ep_pb_plan.leaderPosition
     *
     * @param leaderposition the value for ep_pb_plan.leaderPosition
     *
     * @mbggenerated
     */
    public void setLeaderposition(String leaderposition) {
        this.leaderposition = leaderposition == null ? null : leaderposition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ep_pb_plan.fillDept
     *
     * @return the value of ep_pb_plan.fillDept
     *
     * @mbggenerated
     */
    public String getFilldept() {
        return filldept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ep_pb_plan.fillDept
     *
     * @param filldept the value for ep_pb_plan.fillDept
     *
     * @mbggenerated
     */
    public void setFilldept(String filldept) {
        this.filldept = filldept == null ? null : filldept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ep_pb_plan.demo
     *
     * @return the value of ep_pb_plan.demo
     *
     * @mbggenerated
     */
    public String getDemo() {
        return demo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ep_pb_plan.demo
     *
     * @param demo the value for ep_pb_plan.demo
     *
     * @mbggenerated
     */
    public void setDemo(String demo) {
        this.demo = demo == null ? null : demo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ep_pb_plan.state
     *
     * @return the value of ep_pb_plan.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ep_pb_plan.state
     *
     * @param state the value for ep_pb_plan.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ep_pb_plan.createTime
     *
     * @return the value of ep_pb_plan.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ep_pb_plan.createTime
     *
     * @param createtime the value for ep_pb_plan.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ep_pb_plan.createPerson
     *
     * @return the value of ep_pb_plan.createPerson
     *
     * @mbggenerated
     */
    public String getCreateperson() {
        return createperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ep_pb_plan.createPerson
     *
     * @param createperson the value for ep_pb_plan.createPerson
     *
     * @mbggenerated
     */
    public void setCreateperson(String createperson) {
        this.createperson = createperson == null ? null : createperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ep_pb_plan.updateTime
     *
     * @return the value of ep_pb_plan.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ep_pb_plan.updateTime
     *
     * @param updatetime the value for ep_pb_plan.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ep_pb_plan.updatePerson
     *
     * @return the value of ep_pb_plan.updatePerson
     *
     * @mbggenerated
     */
    public String getUpdateperson() {
        return updateperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ep_pb_plan.updatePerson
     *
     * @param updateperson the value for ep_pb_plan.updatePerson
     *
     * @mbggenerated
     */
    public void setUpdateperson(String updateperson) {
        this.updateperson = updateperson == null ? null : updateperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ep_pb_plan.exportStatus
     *
     * @return the value of ep_pb_plan.exportStatus
     *
     * @mbggenerated
     */
    public String getExportstatus() {
        return exportstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ep_pb_plan.exportStatus
     *
     * @param exportstatus the value for ep_pb_plan.exportStatus
     *
     * @mbggenerated
     */
    public void setExportstatus(String exportstatus) {
        this.exportstatus = exportstatus == null ? null : exportstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ep_pb_plan.exportLog
     *
     * @return the value of ep_pb_plan.exportLog
     *
     * @mbggenerated
     */
    public String getExportlog() {
        return exportlog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ep_pb_plan.exportLog
     *
     * @param exportlog the value for ep_pb_plan.exportLog
     *
     * @mbggenerated
     */
    public void setExportlog(String exportlog) {
        this.exportlog = exportlog == null ? null : exportlog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ep_pb_plan.exportDate
     *
     * @return the value of ep_pb_plan.exportDate
     *
     * @mbggenerated
     */
    public Date getExportdate() {
        return exportdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ep_pb_plan.exportDate
     *
     * @param exportdate the value for ep_pb_plan.exportDate
     *
     * @mbggenerated
     */
    public void setExportdate(Date exportdate) {
        this.exportdate = exportdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ep_pb_plan.fillPersonName
     *
     * @return the value of ep_pb_plan.fillPersonName
     *
     * @mbggenerated
     */
    public String getFillpersonname() {
        return fillpersonname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ep_pb_plan.fillPersonName
     *
     * @param fillpersonname the value for ep_pb_plan.fillPersonName
     *
     * @mbggenerated
     */
    public void setFillpersonname(String fillpersonname) {
        this.fillpersonname = fillpersonname == null ? null : fillpersonname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ep_pb_plan.fillPersonPhone
     *
     * @return the value of ep_pb_plan.fillPersonPhone
     *
     * @mbggenerated
     */
    public String getFillpersonphone() {
        return fillpersonphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ep_pb_plan.fillPersonPhone
     *
     * @param fillpersonphone the value for ep_pb_plan.fillPersonPhone
     *
     * @mbggenerated
     */
    public void setFillpersonphone(String fillpersonphone) {
        this.fillpersonphone = fillpersonphone == null ? null : fillpersonphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ep_pb_plan.expLogId
     *
     * @return the value of ep_pb_plan.expLogId
     *
     * @mbggenerated
     */
    public String getExplogid() {
        return explogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ep_pb_plan.expLogId
     *
     * @param explogid the value for ep_pb_plan.expLogId
     *
     * @mbggenerated
     */
    public void setExplogid(String explogid) {
        this.explogid = explogid == null ? null : explogid.trim();
    }
}